import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://clone-groupon-incremental-30.coupadev.com/sessions/new');
  await page.getByLabel('Username or Email Address').fill('analytics_admin_user_login');
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').fill('Temp@1234');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.goto('https://clone-groupon-incremental-30.coupadev.com/analytics');
  await page.getByRole('link', { name: 'AP Manager - Program Efficiency' }).click();
  await page.frameLocator('#analytics_iframe').getByRole('button', { name: 'is in the last 12 months' }).click();
  await page.frameLocator('#analytics_iframe').getByRole('textbox').first().click();
  await page.frameLocator('#analytics_iframe').getByRole('option', { name: 'is any time' }).click();
  await page.frameLocator('#analytics_iframe').getByRole('textbox').click();
  await page.frameLocator('#analytics_iframe').getByRole('option', { name: 'is any time' }).locator('span').click();
  await page.frameLocator('#analytics_iframe').getByRole('textbox').click();
  await page.frameLocator('#analytics_iframe').getByRole('option', { name: 'is any time' }).locator('span').click();
  await page.frameLocator('#analytics_iframe').getByRole('textbox').click();
  await page.frameLocator('#analytics_iframe').getByRole('option', { name: 'is any time' }).locator('span').click();
  await page.frameLocator('#analytics_iframe').getByRole('button', { name: 'Update' }).click();
  await page.frameLocator('#analytics_iframe').getByRole('region', { name: 'Invoices in Progress' }).getByRole('button').nth(1).click();
  await page.frameLocator('#analytics_iframe').getByRole('menuitem', { name: 'Download data' }).click();
  const page3Promise = page.waitForEvent('popup');
  await page.frameLocator('#analytics_iframe').getByRole('button', { name: 'Open in Browser' }).click();
  const page3 = await page3Promise;
  await page.frameLocator('#analytics_iframe').getByRole('region', { name: 'Invoices in Progress' }).getByRole('button').nth(1).click();
  await page.frameLocator('#analytics_iframe').getByRole('menuitem', { name: 'Download data' }).click();
  await page.frameLocator('#analytics_iframe').getByTestId('caret').locator('svg').click();
  await page.frameLocator('#analytics_iframe').getByText('PNG (Image of Visualization)').click();
  const page4Promise = page.waitForEvent('popup');
  await page.frameLocator('#analytics_iframe').getByRole('button', { name: 'Download' }).click();
  const page4 = await page4Promise;
  await page4.goto('https://coupadev.looker.com/render/process/l/800/600/query-visualization/ZhoRaRuhWpNa12jFzG0ssI.png?qid=ZhoRaRuhWpNa12jFzG0ssI&download=yes&title=Invoices%20in%20Progress&filename=Invoices%20in%20Progress.png');
  await page.frameLocator('#analytics_iframe').getByLabel('Invoice Cycle Time').getByRole('button', { name: 'Tile actions' }).click();
  const download3Promise = page.waitForEvent('download');
  await page.frameLocator('#analytics_iframe').getByRole('button', { name: 'Download' }).click();
  const download3 = await download3Promise;
  await page.frameLocator('#analytics_iframe').getByRole('button', { name: 'Dashboard actions' }).click();
  await page.frameLocator('#analytics_iframe').getByRole('menuitem', { name: 'Download ⇧⌘D' }).click();
  await page.frameLocator('#analytics_iframe').getByRole('button', { name: 'Download' }).click();
  await page.frameLocator('#analytics_iframe').getByRole('region', { name: 'Invoices in Progress' }).getByRole('button').nth(1).click();
  await page.frameLocator('#analytics_iframe').getByRole('menuitem', { name: 'Download data' }).click();
  await page.frameLocator('#analytics_iframe').getByRole('banner', { name: 'Download Invoices in Progress' }).click();
  const download5Promise = page.waitForEvent('download');
  await page.frameLocator('#analytics_iframe').getByRole('button', { name: 'Download' }).click();
  const download5 = await download5Promise;
});